apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-preview-apps
  namespace: default
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        github:
          # The GitHub organization or user
          owner: himeshpanc
          # The repository to scan for pull requests
          repo: "*"
          # Reference to the secret containing the token
          tokenRef:
            secretName: github-pr-token
            key: token
          # Labels to filter PRs
          labels:
            - preview-env
        requeueAfterSeconds: 180  # Check every 3 minutes
  template:
    metadata:
      name: '{{.repository}}-pr-{{.number}}'
      labels:
        preview: "true"
        pr-number: "{{.number}}"
    spec:
      project: default
      source:
        repoURL: '{{.source.repoURL}}'
        targetRevision: '{{.head_sha}}'
        path: apollo-app/charts/apollo
        helm:
          valueFiles:
            - values.yaml
          # Optional: Add PR-specific values
          values: |
            environment: preview
            prNumber: "{{.number}}"
            branch: "{{.branch}}"
      destination:
        name: himesh-corp-mac
        # Create namespace per PR
        namespace: '{{.repository}}-pr-{{.number}}'
      syncPolicy:
        automated:
          prune: true  # Automatically delete resources
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pr-preview-placeholder
  namespace: argocd
data:
  info: "PR Preview ApplicationSet is active and monitoring for labeled PRs"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet