apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-preview-apps
  namespace: argocd
  annotations:
    description: "Automatically creates preview environments for pull requests"
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        github:
          owner: himeshpanc
          repo: "rocket-apps"
          tokenRef:
            secretName: github-pr-token
            key: token
          labels:
            - preview-env
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'rocket-apps-pr-{{.number}}'
      labels:
        preview: "true"
        pr-number: "{{.number}}"
        repo: "rocket-apps"
    spec:
      project: default
      source:
        repoURL: '{{.source.repoURL}}'
        targetRevision: '{{.head_sha}}'
        path: 'apollo-app/charts/apollo'
        helm:
          valueFiles:
            - values.yaml
          values: |
            global:
              environment: preview
              prNumber: "{{.number}}"
              repository: "rocket-apps"
              commitSha: "{{.head_sha}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'preview-rocket-apps-{{.number}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true