# Default values for PR preview environments
environment: preview

# Application configuration
resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"

# Preview environment specific settings
prNumber: ""
branch: ""

# Deployment configuration
replicaCount: 1
image:
  pullPolicy: Always

# Service configuration
service:
  type: ClusterIP
  port: 80

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: "pr-{{ .Values.prNumber }}.preview.yourdomain.com"
      paths:
        - path: /
          pathType: Prefix
